# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "google-safe-browsing-plugin"
  s.version = "0.1.2"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Lonex"]
  s.date = "2013-06-20"
  s.description = "A Ruby implementation of the Google Safe Browsing v2. Rails is the dependency mainly because of the data layer."
  s.email = "stonelonely@gmail.com"
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.md"
  ]
  s.files = [
    "lib/faraday/response/safe_browsing_update_parser.rb",
    "lib/google/safe_browsing_client.rb",
    "lib/google/safe_browsing_parser.rb",
    "lib/google/safe_browsing_update_helper.rb",
    "lib/google/sha_util.rb",
    "lib/google/url_canonicalizer.rb",
    "lib/google/url_scramble.rb",
    "lib/google_safe_browsing_plugin.rb",
    "lib/rails/generators/google/config/config_generator.rb",
    "lib/rails/generators/google/config/templates/google_safe_browsing.yml",
    "lib/rails/generators/google/helper/helper_generator.rb",
    "lib/rails/generators/google/helper/templates/safe_browsing_helper.rb",
    "lib/rails/generators/google/install_generator.rb",
    "lib/rails/generators/google/model/model_generator.rb",
    "lib/rails/generators/google/model/templates/create_google_functions.rb",
    "lib/rails/generators/google/model/templates/create_google_safe_browsing_full_hash_requests.rb",
    "lib/rails/generators/google/model/templates/create_google_safe_browsing_full_hashes.rb",
    "lib/rails/generators/google/model/templates/create_google_safe_browsing_list.rb",
    "lib/rails/generators/google/model/templates/create_google_safe_browsing_redirect_urls.rb",
    "lib/rails/generators/google/model/templates/create_google_safe_browsing_shavar.rb",
    "lib/rails/generators/google/model/templates/google.rb",
    "lib/rails/generators/google/model/templates/google/error.rb",
    "lib/rails/generators/google/model/templates/google/function.rb",
    "lib/rails/generators/google/model/templates/google/safe_browsing_full_hash.rb",
    "lib/rails/generators/google/model/templates/google/safe_browsing_full_hash_request.rb",
    "lib/rails/generators/google/model/templates/google/safe_browsing_list.rb",
    "lib/rails/generators/google/model/templates/google/safe_browsing_redirect_url.rb",
    "lib/rails/generators/google/model/templates/google/safe_browsing_shavar.rb",
    "lib/rails/generators/google/model/templates/google/safe_browsing_update.rb",
    "lib/rails/generators/google/rspec/rspec_generator.rb",
    "lib/rails/generators/google/rspec/templates/bin_sample_1.data",
    "lib/rails/generators/google/rspec/templates/bin_sample_2.data",
    "lib/rails/generators/google/rspec/templates/full_hash_parse_spec.rb",
    "lib/rails/generators/google/rspec/templates/full_hash_response_0.data",
    "lib/rails/generators/google/rspec/templates/full_hash_response_1.data",
    "lib/rails/generators/google/rspec/templates/full_hash_response_2.data",
    "lib/rails/generators/google/rspec/templates/full_hash_response_3.data",
    "lib/rails/generators/google/rspec/templates/shavar_encode_data_parse_spec.rb",
    "lib/rails/generators/google/rspec/templates/shavar_list_info_parse_spec.rb",
    "lib/safe_browsing_task.rb",
    "lib/tasks/google.rake"
  ]
  s.homepage = "http://github.com/lonex/google-safe-browsing-plugin"
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.25"
  s.summary = "Rails plugin for Google Safe Browsing"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<activesupport>, [">= 2.3.0"])
      s.add_development_dependency(%q<faraday>, ["~> 0.8"])
      s.add_development_dependency(%q<rspec>, ["= 2.8.0"])
      s.add_development_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_development_dependency(%q<bundler>, ["~> 1.2.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.8.4"])
      s.add_runtime_dependency(%q<faraday>, ["~> 0.8.7"])
      s.add_runtime_dependency(%q<activesupport>, [">= 2.3.0"])
    else
      s.add_dependency(%q<activesupport>, [">= 2.3.0"])
      s.add_dependency(%q<faraday>, ["~> 0.8"])
      s.add_dependency(%q<rspec>, ["= 2.8.0"])
      s.add_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_dependency(%q<bundler>, ["~> 1.2.0"])
      s.add_dependency(%q<jeweler>, ["~> 1.8.4"])
      s.add_dependency(%q<faraday>, ["~> 0.8.7"])
      s.add_dependency(%q<activesupport>, [">= 2.3.0"])
    end
  else
    s.add_dependency(%q<activesupport>, [">= 2.3.0"])
    s.add_dependency(%q<faraday>, ["~> 0.8"])
    s.add_dependency(%q<rspec>, ["= 2.8.0"])
    s.add_dependency(%q<rdoc>, ["~> 3.12"])
    s.add_dependency(%q<bundler>, ["~> 1.2.0"])
    s.add_dependency(%q<jeweler>, ["~> 1.8.4"])
    s.add_dependency(%q<faraday>, ["~> 0.8.7"])
    s.add_dependency(%q<activesupport>, [">= 2.3.0"])
  end
end

